print("Hello there, what is your name ?")
name = input()
print("Hello" +" " + name + " " + "how old are you ?")
age = input()
print(" And when were you born? ")
DOB = input()
print("Perfect !  now what is your address ? ")
address = input()
print("That is perfect, do you have any hobbies ? ")
hobbies = input()
print("Thank you very much ! Would you like a recap ?")
recap = input()
print( name + " is " + age +" years old and was born in " + DOB + ", lives at "+address +" and his hobies are " + hobbies + ". Are these details correct? " )

all_good = input()
print("Thank you and have a nice day")